---
version: "3.8"
x-nautobot-build: &nautobot-build
  build:
    args:
      NAUTOBOT_VERSION: "${NAUTOBOT_VERSION}"
      PYTHON_VER: "${PYTHON_VER}"
    context: "../"
    target: "nautobot"
    dockerfile: "environments/Dockerfile-LDAP"
x-nautobot-base: &nautobot-base
  image: "test/nautobot-ldap"
  env_file:
    - "local.env"
    - "creds.env"
  tty: true

services:
  nautobot:
    depends_on:
      - "db"
      - "redis"
    <<: [*nautobot-base, *nautobot-build]
    volumes:
      - "../config/nautobot_config.py.ldap:/opt/nautobot/nautobot_config.py:ro"
    #   - "./nautobot.key:/opt/nautobot/nautobot.key:ro"
    #   - "./nautobot.crt:/opt/nautobot/nautobot.crt:ro"
  celery_worker:
    entrypoint:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_LOG_LEVEL from the env
      - "nautobot-server celery worker -l $$NAUTOBOT_LOG_LEVEL --events"  ## $$ because of docker-compose
    depends_on:
      - "nautobot"
    healthcheck:
      interval: "30s"
      timeout: "10s"
      start_period: "30s"
      retries: 3
      test:
        [
          "CMD",
          "bash",
          "-c",
          "nautobot-server celery inspect ping --destination celery@$$HOSTNAME"  ## $$ because of docker-compose
        ]
    <<: *nautobot-base
  celery_beat:
    entrypoint:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_LOG_LEVEL from the env
      - "nautobot-server celery beat -l $$NAUTOBOT_LOG_LEVEL"  ## $$ because of docker-compose
    depends_on:
      - "nautobot"
    healthcheck:
      disable: true
    <<: *nautobot-base
  # ---------------------------------
  redis:
    image: "redis:alpine"
    env_file:
      - "local.env"
      - "creds.env"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD"  ## $$ because of docker-compose
    restart: "unless-stopped"
  ldap:
    image: "osixia/openldap:1.5.0"
    environment:
      LDAP_ORGANISATION: "planetexpress"
      LDAP_DOMAIN: "planetexpress.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_BASE_DN: "dc=planetexpress,dc=com"
      LDAP_SEED_INTERNAL_LDIF_PATH: "/tmp/directory.ldif"
      LOG_LEVEL: "debug"
      log_level: "debug"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - "./directory.ldif:/tmp/directory.ldif"
    restart: "unless-stopped"


